#!/usr/bin/python3

import sys  # We need sys so that we can pass argv to QApplication
import os
import time
import yaml
import numpy as np
import pyqtgraph as pg
from random import randint
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from pathlib import Path
from PyQt5 import QtWidgets, QtCore, QtGui
import matplotlib.pyplot as plt
import walksignal.dataset as ds
import walksignal.models as md
import walksignal.plottools as pt
import walksignal.utils as utils
import walksignal.config as cfg
import walksignal.gui.tablemodel as tm
import walksignal.gui.parameterwidget as pw

class WSWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super(WSWindow, self).__init__(*args, **kwargs)

        self.setWindowTitle("walksignal 0.8.0")
        self.config = cfg.Config("lastcfg.yaml")

        self.signal_dataset = None
        self.bitrate_dataset = None
        self.x_range = None
        self.y_range = None

        self.cell = None
        self.cell_pl = None
        self.cell_distances = None
        self.tower = None
        self.cbar = None

        self.br_distances = None

        self.pl_points = np.arange(0.5, 2500, 0.5)
        self.pl_fs_y = None

        self.pl_red_pen = pg.mkPen(color=(255, 0, 0), width=1)
        self.pl_green_pen = pg.mkPen(color=(64, 192, 64), width=1)
        self.pl_blue_pen = pg.mkPen(color=(0, 0, 255), width=1)
        self.pl_solid_pen = pg.mkPen(color=(0, 0, 0), width=3, style=QtCore.Qt.SolidLine)
        self.pl_dot_pen = pg.mkPen(color=(255, 144, 0), width=3, style=QtCore.Qt.DotLine)
        self.pl_dash_pen = pg.mkPen(color=(128, 64, 64), width=3, style=QtCore.Qt.DashLine)
        self.pl_dashdot_pen = pg.mkPen(color=(192,64,192), width=3, style=QtCore.Qt.DashDotLine)
        self.pl_dashdotdot_pen = pg.mkPen(color=(64, 64, 144), width=3, style=QtCore.Qt.DashDotDotLine)

        self.styles = {'color':'b', 'font-size':'18px'}
        self.x = list(range(100))  # 100 time points
        self.y = [randint(0,100) for _ in range(100)]  # 100 data points

        self.setupUI()
    
    def closeEvent(self, event):
        self.config.save()

    def setupCanvases(self):
        self.signal_map_canvas = pt.MplCanvas(self, width=5, height=4, dpi=100)
        self.signal_map_toolbar = NavigationToolbar(self.signal_map_canvas, self)

        self.signal_cm = plt.cm.get_cmap('gist_heat')

        self.bitrate_map_canvas = pt.MplCanvas(self, width=5, height=4, dpi=100)
        self.bitrate_map_toolbar = NavigationToolbar(self.bitrate_map_canvas, self)

    def setupUI(self):
        self.setupCanvases()
        self.setupPlotWidgets()
        self.setupLines()
        self.setupFileControls()
        self.setupCellControls()
        self.setupPathLossControls()
        self.setupTabs()
        self.setupDataSidebar()

        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.addWidget(self.dataSidebarWidget, 1)
        self.main_layout.addWidget(self.tabs, 3)
        self.br_widget = QtWidgets.QWidget()
        self.br_widget.setLayout(self.main_layout)
        self.setCentralWidget(self.br_widget)
        if self.config.signal_data_files:
            self.setSignalData()
            self.loadCell()

        if self.config.bitrate_data_files:
            self.setBitrateData()

    def setupPlotWidgets(self):
        self.br_widget = pg.PlotWidget()
        self.br_widget.addLegend(offset=(300, 210))
        self.br_widget.setBackground('w')
        self.br_widget.showGrid(x=True, y=True, alpha=0.5)
        self.br_widget.setYRange(0, 250)
        self.br_widget.setLabel('left', "Bitrate (Mb/s)", **self.styles)
        self.br_widget.setLabel('bottom', "Distance (m)", **self.styles)

        self.pl_widget = pg.PlotWidget()
        self.pl_widget.addLegend(offset=(300, 210))
        self.pl_widget.setBackground('w')
        self.pl_widget.showGrid(x=True, y=True, alpha=0.5)
        self.pl_widget.setYRange(-150, 150)
        self.pl_widget.setLabel('left', "Path Loss (dB)", **self.styles)
        self.pl_widget.setLabel('bottom', "Distance (m)", **self.styles)

    def setupLines(self):
        self.pl_abg_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_blue_pen, name="ABG Model")
        self.pl_ci_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_green_pen, name="CI Model")
        self.pl_fs_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_solid_pen, name="Free Space Model")
        self.pl_tworay_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_dot_pen, name="TwoRay Model")
        self.pl_oh_u_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_dash_pen, name="Okumura-Hata Urban")
        self.pl_oh_s_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_dashdot_pen, name="Okumura-Hata Suburban")
        self.pl_oh_r_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_dashdotdot_pen, name="Okumura-Hata Rural")
        self.pl_measured_line = self.pl_widget.plot(self.x, self.y, pen=None, symbol="o", symbolPen=self.pl_red_pen, symbolSize=3, symbolBrush=(255, 0, 0, 255), name="Measured")

        self.br_up_line = self.br_widget.plot(self.x, self.y, pen=None, symbol="o", symbolPen=self.pl_blue_pen, symbolSize=5, symbolBrush=(0, 0, 255, 255), name="Upload")
        self.br_down_line = self.br_widget.plot(self.x, self.y, pen=None, symbol="o", symbolPen=self.pl_red_pen, symbolSize=5, symbolBrush=(255, 0, 0, 255), name="Download")

    def setupFileControls(self):
        self.file_control_box = QtWidgets.QVBoxLayout()
        self.file_load_box = QtWidgets.QHBoxLayout()

        self.file_controls_title = QtWidgets.QLabel('File Selection')
        self.file_controls_title.setFont(QtGui.QFont('Arial', 16))

        self.set_signal_data_button = QtWidgets.QPushButton('Set Signal')
        self.set_signal_data_button.clicked.connect(self.showSignalFileDialog)

        self.set_bitrate_data_button = QtWidgets.QPushButton('Set Bitrate')
        self.set_bitrate_data_button.clicked.connect(self.showBitrateFileDialog)

        self.file_load_box.addWidget(self.set_signal_data_button)
        self.file_load_box.addWidget(self.set_bitrate_data_button)
        self.file_control_box.addWidget(self.file_controls_title)
        self.file_control_box.addLayout(self.file_load_box)

    def setupPathLossControls(self):
        self.control_tabs = QtWidgets.QTabWidget()

        self.pl_sidebar_box = QtWidgets.QVBoxLayout()
        self.pl_general_controls_box = QtWidgets.QVBoxLayout()
        self.pl_oh_title_box = QtWidgets.QHBoxLayout()
        self.pl_freq_box = QtWidgets.QHBoxLayout()
        self.pl_alpha_box = QtWidgets.QHBoxLayout()
        self.pl_beta_box = QtWidgets.QHBoxLayout()
        self.pl_gamma_box = QtWidgets.QHBoxLayout()
        self.pl_sigma_box = QtWidgets.QHBoxLayout()
        self.pl_exp_box = QtWidgets.QHBoxLayout()
        self.pl_exp_tworay_box = QtWidgets.QHBoxLayout()
        self.pl_tx_power_box = QtWidgets.QHBoxLayout()
        self.pl_tx_gain_box = QtWidgets.QHBoxLayout()
        self.pl_rx_gain_box = QtWidgets.QHBoxLayout()
        self.pl_ref_dist_box = QtWidgets.QHBoxLayout()
        self.pl_ref_pl_box = QtWidgets.QHBoxLayout()
        self.pl_bs_height_box = QtWidgets.QHBoxLayout()
        self.pl_ue_height_box = QtWidgets.QHBoxLayout()

        self.setupGeneralPathLossControlsBox()
        self.setupLatLonBoxes()

        self.pl_sidebar_box.addLayout(self.pl_general_controls_box)
        self.pl_sidebar_box.setAlignment(QtCore.Qt.AlignTop)

    def setupGeneralPathLossControlsBox(self):
        self.pl_general_controls_box = QtWidgets.QVBoxLayout()

        self.pl_controls_title = QtWidgets.QLabel("Controls")
        self.pl_controls_title.setFont(QtGui.QFont("Arial", 14))

        self.pl_fs_checkbox = QtWidgets.QCheckBox("FS")
        self.pl_fs_checkbox.setChecked(True)
        self.pl_fs_checkbox.stateChanged.connect(self.plCheckboxUpdate)

        self.pl_tworay_checkbox = QtWidgets.QCheckBox("TwoRay")
        self.pl_tworay_checkbox.setChecked(True)
        self.pl_tworay_checkbox.stateChanged.connect(self.plCheckboxUpdate)

        self.pl_path_gain_checkbox = QtWidgets.QCheckBox("Plot as Gain")
        self.pl_path_gain_checkbox.setChecked(False)
        self.pl_path_gain_checkbox.stateChanged.connect(self.plCheckboxUpdate)

        self.pl_abg_checkbox = QtWidgets.QCheckBox("ABG")
        self.pl_abg_checkbox.setChecked(True)
        self.pl_abg_checkbox.stateChanged.connect(self.plCheckboxUpdate)

        self.pl_ci_checkbox = QtWidgets.QCheckBox("CI")
        self.pl_ci_checkbox.setChecked(False)
        self.pl_ci_checkbox.stateChanged.connect(self.plCheckboxUpdate)

        self.pl_model_layout = QtWidgets.QHBoxLayout()
        self.pl_model_layout.addWidget(self.pl_fs_checkbox)
        self.pl_model_layout.addWidget(self.pl_tworay_checkbox)
        self.pl_model_layout.addWidget(self.pl_abg_checkbox)
        self.pl_model_layout.addWidget(self.pl_ci_checkbox)

        self.pl_oh_u_checkbox = QtWidgets.QCheckBox("OH Urban")
        self.pl_oh_u_checkbox.setChecked(False)
        self.pl_oh_u_checkbox.stateChanged.connect(self.plCheckboxUpdate)

        self.pl_oh_s_checkbox = QtWidgets.QCheckBox("OH Suburban")
        self.pl_oh_s_checkbox.setChecked(False)
        self.pl_oh_s_checkbox.stateChanged.connect(self.plCheckboxUpdate)

        self.pl_oh_r_checkbox = QtWidgets.QCheckBox("OH Rural")
        self.pl_oh_r_checkbox.setChecked(False)
        self.pl_oh_r_checkbox.stateChanged.connect(self.plCheckboxUpdate)

        self.pl_oh_checkbox_layout = QtWidgets.QHBoxLayout()
        self.pl_oh_checkbox_layout.addWidget(self.pl_oh_u_checkbox)
        self.pl_oh_checkbox_layout.addWidget(self.pl_oh_s_checkbox)
        self.pl_oh_checkbox_layout.addWidget(self.pl_oh_r_checkbox)

        self.pl_large_city_checkbox = QtWidgets.QCheckBox("Large City")
        self.pl_large_city_checkbox.setChecked(True)
        self.pl_large_city_checkbox.stateChanged.connect(self.plCheckboxUpdate)

        self.pl_freq_textbox = QtWidgets.QLineEdit(self)
        if self.config:
            self.pl_freq_textbox.setText(str(self.config.pl_freq_value))
        else:
            self.pl_freq_textbox.setText("50")
        self.pl_freq_textbox_label = QtWidgets.QLabel('f')
        self.pl_freq_unit_label = QtWidgets.QLabel('MHz')
        self.pl_freq_textbox.editingFinished.connect(self.plTextboxUpdate)
        self.pl_freq_box.addWidget(self.pl_freq_textbox_label)
        self.pl_freq_box.addWidget(self.pl_freq_textbox)
        self.pl_freq_box.addWidget(self.pl_freq_unit_label)

        self.pl_ref_pl_textbox = QtWidgets.QLineEdit(self)
        self.pl_ref_pl_textbox.setText("1")
        self.pl_ref_pl_textbox_label = QtWidgets.QLabel('PL<sub>ref</sub> (2R)')
        self.pl_ref_pl_unit_label = QtWidgets.QLabel('dB')
        self.pl_ref_pl_textbox.editingFinished.connect(self.plTextboxUpdate)
        self.pl_ref_pl_box.addWidget(self.pl_ref_pl_textbox_label)
        self.pl_ref_pl_box.addWidget(self.pl_ref_pl_textbox)
        self.pl_ref_pl_box.addWidget(self.pl_ref_pl_unit_label)

        self.pl_exp_tworay_parameter = pw.ParameterWidget("\u03BD (2R)", "", self.config.pl_exp_tworay_value, 0, 100, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_exp_tworay_box.addWidget(self.pl_exp_tworay_parameter)
        self.pl_tx_power_parameter = pw.ParameterWidget("P<sub>TX</sub>", "dBm", self.config.pl_tx_power_value, 0, 1000, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_tx_power_box.addWidget(self.pl_tx_power_parameter)
        self.pl_tx_gain_parameter = pw.ParameterWidget("G<sub>TX</sub>", "dB", self.config.pl_tx_gain_value, 0, 1000, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_tx_gain_box.addWidget(self.pl_tx_gain_parameter)
        self.pl_rx_gain_parameter = pw.ParameterWidget("G<sub>RX</sub>", "dB", self.config.pl_rx_gain_value, 0, 1000, 10, self.plSliderUpdate, self.plTextboxUpdate) 
        self.pl_rx_gain_box.addWidget(self.pl_rx_gain_parameter)
        self.pl_alpha_parameter = pw.ParameterWidget("\u03B1", "", self.config.pl_alpha_value, 0, 100, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_alpha_box.addWidget(self.pl_alpha_parameter)
        self.pl_beta_parameter = pw.ParameterWidget("\u03B2", "dB", self.config.pl_beta_value, -1000, 1000, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_beta_box.addWidget(self.pl_beta_parameter)
        self.pl_gamma_parameter = pw.ParameterWidget("\u03B3", "", self.config.pl_gamma_value, 0, 100, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_gamma_box.addWidget(self.pl_gamma_parameter)
        self.pl_sigma_parameter = pw.ParameterWidget("\u03C3", "dB", self.config.pl_sigma_value, 0, 100, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_sigma_box.addWidget(self.pl_sigma_parameter)
        self.pl_exp_parameter = pw.ParameterWidget("\u03BD (CI)", "", self.config.pl_exp_value, 0, 100, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_exp_box.addWidget(self.pl_exp_parameter)

        self.pl_gain_layout = QtWidgets.QHBoxLayout()
        self.pl_gain_layout.addWidget(self.pl_tx_gain_parameter)
        self.pl_gain_layout.addWidget(self.pl_rx_gain_parameter)

        self.pl_ref_dist_textbox = QtWidgets.QLineEdit(self)
        self.pl_ref_dist_textbox.setText("1")
        self.pl_ref_dist_textbox_label = QtWidgets.QLabel("d<sub>0</sub>")
        self.pl_ref_dist_unit_label = QtWidgets.QLabel('m')
        self.pl_ref_dist_textbox.editingFinished.connect(self.plTextboxUpdate)
        self.pl_ref_dist_box.addWidget(self.pl_ref_dist_textbox_label)
        self.pl_ref_dist_box.addWidget(self.pl_ref_dist_textbox)
        self.pl_ref_dist_box.addWidget(self.pl_ref_dist_unit_label)

        self.pl_bs_height_parameter = pw.ParameterWidget("h<sub>TX</sub>", "m", self.config.pl_bs_height_value, 0, 2500, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_bs_height_box.addWidget(self.pl_bs_height_parameter)

        self.pl_ue_height_parameter = pw.ParameterWidget("h<sub>RX</sub>", "m", self.config.pl_ue_height_value, 0, 100, 10, self.plSliderUpdate, self.plTextboxUpdate)
        self.pl_ue_height_box.addWidget(self.pl_ue_height_parameter)

        self.pl_height_layout = QtWidgets.QHBoxLayout()
        self.pl_height_layout.addWidget(self.pl_bs_height_parameter)
        self.pl_height_layout.addWidget(self.pl_ue_height_parameter)

        self.pl_freq_tx_power_layout = QtWidgets.QHBoxLayout()
        self.pl_freq_tx_power_layout.addLayout(self.pl_freq_box)
        self.pl_freq_tx_power_layout.addLayout(self.pl_tx_power_box)

        self.pl_exp_layout = QtWidgets.QHBoxLayout()
        self.pl_exp_layout.addLayout(self.pl_exp_box)
        self.pl_exp_layout.addLayout(self.pl_exp_tworay_box)

        self.pl_ref_layout = QtWidgets.QHBoxLayout()
        self.pl_ref_layout.addLayout(self.pl_ref_pl_box)
        self.pl_ref_layout.addLayout(self.pl_ref_dist_box)

        self.pl_alpha_beta_layout = QtWidgets.QHBoxLayout()
        self.pl_alpha_beta_layout.addLayout(self.pl_alpha_box)
        self.pl_alpha_beta_layout.addLayout(self.pl_beta_box)

        self.pl_gamma_sigma_layout = QtWidgets.QHBoxLayout()
        self.pl_gamma_sigma_layout.addLayout(self.pl_gamma_box)
        self.pl_gamma_sigma_layout.addLayout(self.pl_sigma_box)

        self.pl_general_controls_box.addWidget(self.pl_controls_title)
        self.pl_general_controls_box.addLayout(self.pl_model_layout)
        self.pl_general_controls_box.addLayout(self.pl_oh_checkbox_layout)
        self.pl_general_controls_box.addWidget(self.pl_large_city_checkbox)
        self.pl_general_controls_box.addWidget(self.pl_path_gain_checkbox)
        self.pl_general_controls_box.addLayout(self.pl_freq_tx_power_layout)
        self.pl_general_controls_box.addLayout(self.pl_ref_layout)
        self.pl_general_controls_box.addLayout(self.pl_gain_layout)
        self.pl_general_controls_box.addLayout(self.pl_height_layout)
        self.pl_general_controls_box.addLayout(self.pl_exp_layout)
        self.pl_general_controls_box.addLayout(self.pl_alpha_beta_layout)
        self.pl_general_controls_box.addLayout(self.pl_gamma_sigma_layout)

    def setupBitrateControls(self):
        self.bitrate_box = QtWidgets.QVBoxLayout()
        self.bitrate_title = QtWidgets.QLabel("Bitrate Controls")
        self.bitrate_title.setFont(QtGui.QFont("Arial", 14))

    def setupCellControls(self):
        self.tower_box = QtWidgets.QVBoxLayout()
        self.cell_box = QtWidgets.QVBoxLayout()
        self.cellid_box = QtWidgets.QHBoxLayout()
        self.cellid_text_box = QtWidgets.QHBoxLayout()
        self.mobile_country_codes_box = QtWidgets.QHBoxLayout()
        self.mobile_country_codes_text_box = QtWidgets.QHBoxLayout()
        self.mobile_network_codes_box = QtWidgets.QHBoxLayout()
        self.mobile_network_codes_text_box = QtWidgets.QHBoxLayout()
        self.local_area_codes_box = QtWidgets.QHBoxLayout()
        self.local_area_codes_text_box = QtWidgets.QHBoxLayout()
        self.latbox = QtWidgets.QHBoxLayout()
        self.lonbox = QtWidgets.QHBoxLayout()
        self.set_tower_box = QtWidgets.QHBoxLayout()

        self.tower_combo_title = QtWidgets.QLabel('Cell Selection')
        self.tower_combo_title.setFont(QtGui.QFont('Arial', 14))

        self.cellid_label = QtWidgets.QLabel('Cell IDs')
        self.cellid_count = QtWidgets.QLabel('')
        self.cellid_combo = QtWidgets.QComboBox(self)

        self.mobile_country_codes_label = QtWidgets.QLabel('MCCs')
        self.mobile_country_codes_count = QtWidgets.QLabel('')
        self.mobile_country_codes_combo = QtWidgets.QComboBox(self)

        self.mobile_network_codes_label = QtWidgets.QLabel('MNCs')
        self.mobile_network_codes_count = QtWidgets.QLabel('')
        self.mobile_network_codes_combo = QtWidgets.QComboBox(self)

        self.local_area_codes_label = QtWidgets.QLabel('LACs')
        self.local_area_codes_count = QtWidgets.QLabel('')
        self.local_area_codes_combo = QtWidgets.QComboBox(self)

        self.cellid_combo.activated.connect(self.setCell)

        self.cellid_text_box.addWidget(self.cellid_label)
        self.cellid_text_box.addWidget(self.cellid_count)
        self.cellid_box.addLayout(self.cellid_text_box)
        self.cellid_box.addWidget(self.cellid_combo)
        self.mobile_country_codes_text_box.addWidget(self.mobile_country_codes_label)
        self.mobile_country_codes_text_box.addWidget(self.mobile_country_codes_count)
        self.mobile_country_codes_box.addLayout(self.mobile_country_codes_text_box)
        self.mobile_country_codes_box.addWidget(self.mobile_country_codes_combo)
        self.mobile_network_codes_text_box.addWidget(self.mobile_network_codes_label)
        self.mobile_network_codes_text_box.addWidget(self.mobile_network_codes_count)
        self.mobile_network_codes_box.addLayout(self.mobile_network_codes_text_box)
        self.mobile_network_codes_box.addWidget(self.mobile_network_codes_combo)
        self.local_area_codes_text_box.addWidget(self.local_area_codes_label)
        self.local_area_codes_text_box.addWidget(self.local_area_codes_count)
        self.local_area_codes_box.addLayout(self.local_area_codes_text_box)
        self.local_area_codes_box.addWidget(self.local_area_codes_combo)
        self.cell_load_button = QtWidgets.QPushButton('Load Cell Data')
        self.cell_load_button.clicked.connect(self.loadCell)
        
        self.cell_box.addLayout(self.mobile_country_codes_box)
        self.cell_box.addLayout(self.mobile_network_codes_box)
        self.cell_box.addLayout(self.local_area_codes_box)
        self.cell_box.addLayout(self.cellid_box)
        self.tower_box.addWidget(self.tower_combo_title)
        self.tower_box.addLayout(self.cell_box)
        self.tower_box.addWidget(self.cell_load_button)
        self.tower_box.addLayout(self.latbox)
        self.tower_box.addLayout(self.lonbox)
        self.tower_box.addLayout(self.set_tower_box)
        self.tower_box.setAlignment(QtCore.Qt.AlignTop)

    def createSummaryTab(self):
        self.summary_scroll_area = QtWidgets.QScrollArea()
        self.summary_scroll_area.setWidgetResizable(True)
        self.overall_summary_table = QtWidgets.QTableView()
        self.overall_summary_table.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed))
        self.overall_summary_title = QtWidgets.QLabel("Overall Statistics")
        self.overall_summary_title.setFont(QtGui.QFont("Arial", 16))
        self.summary_data_box = QtWidgets.QVBoxLayout()
        self.summary_data_box.addWidget(self.overall_summary_title)
        self.summary_data_box.addWidget(self.overall_summary_table)
        self.summary_data_widget = QtWidgets.QWidget()
        self.summary_data_widget.setLayout(self.summary_data_box)
        self.summary_scroll_area.setWidget(self.summary_data_widget)
        self.summary_data_tab = self.summary_scroll_area

    def createCellStatsTab(self):
        self.cellstats_scroll_area = QtWidgets.QScrollArea()
        self.cellstats_scroll_area.setWidgetResizable(True)
        self.overall_cellstats_title = QtWidgets.QLabel("Statistics by Cell")
        self.overall_cellstats_title.setFont(QtGui.QFont("Arial", 16))
        self.cellstats_data_box = QtWidgets.QVBoxLayout()
        self.cellstats_data_box.addWidget(self.overall_cellstats_title)
        self.cellstats_data_widget = QtWidgets.QWidget()
        self.cellstats_data_widget.setLayout(self.cellstats_data_box)
        self.cellstats_scroll_area.setWidget(self.cellstats_data_widget)
        self.cellstats_data_tab = self.cellstats_scroll_area

    def createSignalMapBox(self):
        self.signal_map_box = QtWidgets.QVBoxLayout()
        self.signal_map_box.addWidget(self.signal_map_toolbar)
        self.signal_map_box.addWidget(self.signal_map_canvas)
        self.signal_map_tab = QtWidgets.QWidget()
        self.signal_map_tab.setLayout(self.signal_map_box)

    def createRawDataTab(self):
        self.raw_data_table = QtWidgets.QTableView()
        self.raw_data_box = QtWidgets.QHBoxLayout()
        self.raw_data_box.addWidget(self.raw_data_table)
        self.raw_data_tab = QtWidgets.QWidget()
        self.raw_data_tab.setLayout(self.raw_data_box)

    def createPathLossTab(self):
        self.pl_plot_box = QtWidgets.QHBoxLayout()
        self.pl_plot_box.addWidget(self.pl_widget, 2)
        self.pl_plot_box.addLayout(self.pl_sidebar_box, 1)
        self.pl_plot_tab = QtWidgets.QWidget()
        self.pl_plot_tab.setLayout(self.pl_plot_box)

    def createBitrateMapBox(self):
        self.bitrate_map_box = QtWidgets.QVBoxLayout()
        self.bitrate_map_box.addWidget(self.bitrate_map_toolbar)
        self.bitrate_map_box.addWidget(self.bitrate_map_canvas)
        self.bitrate_map_tab = QtWidgets.QWidget()
        self.bitrate_map_tab.setLayout(self.bitrate_map_box)

    def createBitrateTab(self):
        self.br_plot_tab = self.br_widget

    def setupTabs(self):
        self.tabs = QtWidgets.QTabWidget()

        self.createSummaryTab()
        self.createCellStatsTab()
        self.createSignalMapBox()
        self.createRawDataTab()
        self.createPathLossTab()
        self.createBitrateMapBox()
        self.createBitrateTab()

        self.tabs.addTab(self.summary_data_tab, "Summary")
        self.tabs.addTab(self.cellstats_data_tab, "Cell Stats")
        self.tabs.addTab(self.signal_map_tab, "Signal Map")
        self.tabs.addTab(self.pl_plot_tab, "Path Loss")
        self.tabs.addTab(self.br_plot_tab, "Bitrate")
        self.tabs.addTab(self.bitrate_map_tab, "Bitrate Map")
        self.tabs.addTab(self.raw_data_tab, "Raw Data")

    def setupDataSidebar(self):
        self.dataSidebar = QtWidgets.QVBoxLayout()
        self.dataSidebar.addLayout(self.file_control_box)
        self.dataSidebar.addLayout(self.tower_box)
        self.dataSidebar.addWidget(self.cell_load_button)
        self.dataSidebar.setAlignment(QtCore.Qt.AlignTop)
        self.dataSidebarWidget = QtWidgets.QWidget()
        self.dataSidebarWidget.setLayout(self.dataSidebar)

    def setupLatLonBoxes(self):
        self.lat_edit = QtWidgets.QLineEdit(self)
        if self.config.tower_lat:
            self.lat_edit.setText(str(self.config.tower_lat))
        self.latbox_label = QtWidgets.QLabel("Tower Lat")
        self.latbox.addWidget(self.latbox_label)
        self.latbox.addWidget(self.lat_edit)
        self.lon_edit = QtWidgets.QLineEdit(self)
        if self.config.tower_lon:
            self.lon_edit.setText(str(self.config.tower_lon))
        self.lonbox_label = QtWidgets.QLabel("Tower Lon")
        self.lonbox.addWidget(self.lonbox_label)
        self.lonbox.addWidget(self.lon_edit)

        self.set_tower_button = QtWidgets.QPushButton('Set Tower')
        self.set_tower_button.clicked.connect(self.setTowerLocation)
        self.set_tower_box.addWidget(self.set_tower_button)

    def showSignalFileDialog(self):
        home_dir = str(Path.home)
        fname = QtWidgets.QFileDialog.getOpenFileNames(self, 'Open file', home_dir)

        if fname[0]:
            self.config.signal_data_files = fname[0]

        self.setSignalData()

    def setSignalData(self):
        self.signal_dataset = ds.MeasurementMultiSet(self.config.signal_data_files)
        self.cellid_combo.clear()
        self.mobile_country_codes_combo.clear()
        self.mobile_network_codes_combo.clear()
        self.local_area_codes_combo.clear()
        self.cellid_count.setText("(" + str(len(self.signal_dataset.unique_cellids)) + ")")
        self.mobile_country_codes_count.setText("(" + str(len(self.signal_dataset.unique_mobile_country_codes)) + ")")
        self.mobile_network_codes_count.setText("(" + str(len(self.signal_dataset.unique_mobile_network_codes)) + ")")
        self.local_area_codes_count.setText("(" + str(len(self.signal_dataset.unique_local_area_codes)) + ")")

        for mobile_country_code in self.signal_dataset.unique_mobile_country_codes:
            self.mobile_country_codes_combo.addItem(str(mobile_country_code))
        for mobile_network_code in self.signal_dataset.unique_mobile_network_codes:
            self.mobile_network_codes_combo.addItem(str(mobile_network_code))
        for local_area_code in self.signal_dataset.unique_local_area_codes:
            self.local_area_codes_combo.addItem(str(local_area_code))
        for cellid in self.signal_dataset.unique_cellids:
            self.cellid_combo.addItem(str(cellid))

    def showBitrateFileDialog(self):
        home_dir = str(Path.home)
        fname = QtWidgets.QFileDialog.getOpenFileNames(self, 'Open file', home_dir)

        if fname[0]:
            self.config.bitrate_data_files = fname[0]

        self.setBitrateData()

    def setBitrateData(self):
        self.bitrate_dataset = ds.BitrateMultiSet(self.config.bitrate_data_files)

    def loadCell(self):
        print("Loading cell data...")
        self.setCell()
        self.updateSignalMap()
        self.updateBitrateMap()
        self.updateRawTable()
        self.updateSummaryTable()
        self.updateCellStatsTable()
        self.setTowerLocation()

    def setCell(self):
        self.cell = self.signal_dataset.get_cell(self.cellid_combo.currentText())
        point_count = len(self.cell.signal_power)
        self.cell_load_button.setText("Load Cell Data ({0} points)".format(point_count))

    def setTowerLocation(self):
        if self.lat_edit.text() and self.lon_edit.text():
            self.config.tower_lat = float(self.lat_edit.text())
            self.config.tower_lon = float(self.lon_edit.text())
            self.signal_map_canvas.axes.scatter(float(self.config.tower_lon), float(self.config.tower_lat), zorder=1, alpha=1.0, s=20, color="blue")
            self.signal_map_canvas.draw()

            self.cell_distances = self.cell.get_distances(self.config.tower_lat, self.config.tower_lon)
            self.cell_pl = self.cell.get_path_loss(self.config.pl_tx_power_value)
            
            if self.signal_dataset:
                self.plUpdatePlot()
            if self.bitrate_dataset:
                self.brUpdatePlot()
        else:
            print("Can't draw tower, bad lat/lon")

    def plTextboxUpdate(self):
        self.config.pl_freq_value = float(self.pl_freq_textbox.text())
        self.config.pl_ref_dist_value = float(self.pl_ref_dist_textbox.text())
        self.config.pl_ref_pl_value = float(self.pl_ref_pl_textbox.text())
        self.config.pl_alpha_value = self.pl_alpha_parameter.value
        self.config.pl_beta_value = self.pl_beta_parameter.value
        self.config.pl_gamma_value = self.pl_gamma_parameter.value
        self.config.pl_sigma_value = self.pl_sigma_parameter.value
        self.config.pl_exp_value = self.pl_exp_parameter.value
        self.config.pl_exp_tworay_value = self.pl_exp_tworay_parameter.value
        self.config.pl_tx_power_value = self.pl_tx_power_parameter.value
        self.config.pl_tx_gain_value = self.pl_tx_gain_parameter.value
        self.config.pl_rx_gain_value = self.pl_rx_gain_parameter.value
        self.config.pl_bs_height_value = self.pl_bs_height_parameter.value
        self.config.pl_ue_height_value = self.pl_ue_height_parameter.value
        if self.signal_dataset:
            self.plUpdatePlot()
    
    def plCheckboxUpdate(self):
        if self.pl_large_city_checkbox.isChecked():
            self.config.pl_large_city_state = True
        else:
            self.config.pl_large_city_state = False

        if self.pl_path_gain_checkbox.isChecked():
            self.config.pl_path_gain_state = True
            self.pl_widget.setLabel('left', "Path Gain (dB)", **self.styles)
        else:
            self.config.pl_path_gain_state = False
            self.pl_widget.setLabel('left', "Path Loss (dB)", **self.styles)
        self.plUpdatePlot()

    def plSliderUpdate(self):
        self.config.pl_alpha_value = self.pl_alpha_parameter.value
        self.config.pl_beta_value = self.pl_beta_parameter.value
        self.config.pl_gamma_value = self.pl_gamma_parameter.value
        self.config.pl_sigma_value = self.pl_sigma_parameter.value
        self.config.pl_exp_value = self.pl_exp_parameter.value
        self.config.pl_exp_tworay_value = self.pl_exp_tworay_parameter.value
        self.config.pl_tx_power_value = self.pl_tx_power_parameter.value
        self.config.pl_tx_gain_value = self.pl_tx_gain_parameter.value
        self.config.pl_rx_gain_value = self.pl_rx_gain_parameter.value
        self.config.pl_bs_height_value = self.pl_bs_height_parameter.value
        self.config.pl_ue_height_value = self.pl_ue_height_parameter.value
        if self.signal_dataset:
            self.plUpdatePlot()

    def updateRawTable(self):
        self.raw_table_model = tm.TableModel(self.signal_dataset.data)
        self.raw_data_table.setModel(self.raw_table_model)

    def updateSummaryTable(self):
        for i in reversed(range(self.summary_data_box.count())):
            self.summary_data_box.itemAt(i).widget().setParent(None)

        self.summary_table_model = tm.TableModel(self.signal_dataset.summary)
        self.overall_summary_table.setModel(self.summary_table_model)
        self.summary_data_box.addWidget(self.overall_summary_title)
        self.summary_data_box.addWidget(self.overall_summary_table)
        for index in range(len(self.signal_dataset.set_summaries)):
            set_title = QtWidgets.QLabel(str(self.signal_dataset.file_list[index].rsplit("/", 1)[1]))
            set_title.setFont(QtGui.QFont("Arial", 12))
            view = QtWidgets.QTableView()
            model = tm.TableModel(self.signal_dataset.set_summaries[index])
            view.setModel(model)
            view.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed))
            self.summary_data_box.addWidget(set_title)
            self.summary_data_box.addWidget(view)

    def updateCellStatsTable(self):
        for i in reversed(range(self.cellstats_data_box.count())):
            self.cellstats_data_box.itemAt(i).widget().setParent(None)

        for index in range(len(self.signal_dataset.cellid_subset_summaries)):
            cellid_title = QtWidgets.QLabel(str(self.signal_dataset.unique_cellids[index]))
            cellid_title.setFont(QtGui.QFont("Arial", 12))
            view = QtWidgets.QTableView()
            model = tm.TableModel(self.signal_dataset.cellid_subset_summaries[index])
            view.setModel(model)
            view.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed))
            self.cellstats_data_box.addWidget(cellid_title)
            self.cellstats_data_box.addWidget(view)

    def updateSignalMap(self):
        points = self.cell.data_points
        lon_series = np.array([point.lon for point in points], dtype=float)
        lat_series = np.array([point.lat for point in points], dtype=float)

        if self.cbar:
            self.cbar.remove()
        self.signal_map_canvas.axes.cla()
        divider = make_axes_locatable(self.signal_map_canvas.axes)
        cax = divider.append_axes("right", size="5%", pad=0.1)
        self.signal_map_canvas.axes.imshow(self.signal_dataset.plot_map, zorder=0, extent = self.signal_dataset.map_bbox[0], aspect="equal")
        powerscatter = self.signal_map_canvas.axes.scatter(lon_series, lat_series, zorder=1, alpha=1.0, s=20, c=self.cell.signal_power, cmap=self.signal_cm)

        self.signal_map_canvas.axes.set_xlim(self.signal_dataset.map_bbox[0][0], self.signal_dataset.map_bbox[0][1])
        self.signal_map_canvas.axes.set_ylim(self.signal_dataset.map_bbox[0][2], self.signal_dataset.map_bbox[0][3])
        self.signal_map_canvas.axes.set_xlabel("Longitude")
        self.signal_map_canvas.axes.set_ylabel("Latitude")
        self.signal_map_canvas.axes.set_title("Signal Power vs Position")
        self.signal_map_canvas.axes.ticklabel_format(useOffset=False)
        self.cbar = self.signal_map_canvas.fig.colorbar(powerscatter, cax=cax)
        self.cbar.ax.set_ylabel("Signal Power (dBm)", rotation=270, labelpad=10)

        self.signal_map_canvas.draw()

    def updateBitrateMap(self):
        pass

    def brUpdateMeasurements(self):
        points = self.bitrate_dataset.get_points()
        self.br_distances = [utils.get_distance(bitrate.lat, bitrate.lon, self.config.tower_lat, self.config.tower_lon) * 1000 for bitrate in points]
        self.br_up = [bitrate.up for bitrate in points]
        self.br_down = [bitrate.down for bitrate in points]
        self.br_up_line.setData(self.br_distances, self.br_up)
        self.br_down_line.setData(self.br_distances, self.br_down)

    def brUpdatePlot(self):
        self.brUpdateMeasurements()

    def plUpdatePlot(self):
        self.plUpdateMeasurements()
        self.plUpdateModels()
        self.plUpdatePlotTitle()
        self.plUpdateLegend()

    def plUpdatePlotTitle(self):
        self.pl_widget.setTitle(f"<p \
                style=\"color:black;font-size:14px\">Path Loss for Cell \
                {self.cell.cellid} vs Distance \
                ({self.config.tower_lat},{self.config.tower_lon}), \
                {self.config.pl_freq_value} MHz, G<sub>TX</sub> \
                = {self.config.pl_tx_gain_value} dB, G<sub>RX</sub> = \
                {self.config.pl_rx_gain_value} dB</p>")

    def plUpdateXScale(self):
        self.pl_widget.setXRange(0, max(self.cell_distances) + 50)

    def plUpdateYScale(self):
        if self.config.pl_path_gain_state:
            y_min = max(self.cell_pl) * -1 - 20
            y_max = min(self.cell_pl) * -1 + 20
        else:
            y_min = min(self.cell_pl) - 20
            y_max = max(self.cell_pl) + 20
        self.pl_widget.setYRange(y_min, y_max)

    def plUpdateMeasurements(self):
        self.cell_distances = self.cell.get_distances(self.config.tower_lat, self.config.tower_lon)
        self.cell_pl = self.cell.get_path_loss(self.config.pl_tx_power_value)
        if self.config.pl_path_gain_state:
            measured_inverted = [element * -1 for element in self.cell_pl]
            self.pl_measured_line.setData(self.cell_distances, measured_inverted)
        else:
            self.pl_measured_line.setData(self.cell_distances, self.cell_pl)

    def plUpdateLegend(self):
        self.pl_widget.plotItem.legend.removeItem(self.pl_measured_line)
        self.pl_widget.plotItem.legend.removeItem(self.pl_abg_line)
        self.pl_widget.plotItem.legend.removeItem(self.pl_ci_line)
        self.pl_widget.plotItem.legend.removeItem(self.pl_tworay_line)
        self.pl_widget.plotItem.legend.removeItem(self.pl_oh_u_line)
        self.pl_widget.plotItem.legend.removeItem(self.pl_oh_s_line)
        self.pl_widget.plotItem.legend.removeItem(self.pl_oh_r_line)

        self.pl_widget.plotItem.legend.addItem(self.pl_measured_line, name=f"Measured (tx_power = {self.config.pl_tx_power_value} dBm)")
        self.pl_widget.plotItem.legend.addItem(self.pl_abg_line,
                name=f"ABG (\u03B1 = {self.config.pl_alpha_value}, \
                \u03B2 = {self.config.pl_beta_value}, \u03B3 = \
                {self.config.pl_gamma_value}, d_ref = \
                {self.config.pl_ref_dist_value} m, \u03C3 = \
                {self.config.pl_sigma_value} dB)")
        self.pl_widget.plotItem.legend.addItem(self.pl_ci_line,
                name=f"CI (\u03BD = {self.config.pl_exp_value}, d_ref = \
                {self.config.pl_ref_dist_value} m, \u03C3 = \
                {self.config.pl_sigma_value} dB)")
        self.pl_widget.plotItem.legend.addItem(self.pl_tworay_line,
                name=f"TwoRay (\u03BD = \
                {self.config.pl_exp_tworay_value}, d_ref = \
                {self.config.pl_ref_dist_value} m, pl_ref = \
                {self.config.pl_ref_pl_value} dB)")
        self.pl_widget.plotItem.legend.addItem(self.pl_oh_u_line,
                name=f"OH Urban (bs_height = \
                {self.config.pl_bs_height_value} m, ue_height = \
                {self.config.pl_ue_height_value} m, large_city = \
                {self.config.pl_large_city_state})")
        self.pl_widget.plotItem.legend.addItem(self.pl_oh_s_line,
                name=f"OH Suburban (bs_height = \
                {self.config.pl_bs_height_value} m, ue_height = \
                {self.config.pl_ue_height_value} m, large_city = \
                {self.config.pl_large_city_state})")
        self.pl_widget.plotItem.legend.addItem(self.pl_oh_r_line,
                name=f"OH Rural (bs_height = \
                {self.config.pl_bs_height_value} m, ue_height = \
                {self.config.pl_ue_height_value} m, large_city = \
                {self.config.pl_large_city_state})")

    def plUpdateModels(self):
        if self.pl_fs_checkbox.isChecked():
            self.fs_model = md.FreeSpaceModel(self.config.pl_freq_value)
            self.fs_y = self.fs_model.path_loss_array(self.pl_points) - self.config.pl_tx_gain_value - self.config.pl_rx_gain_value
            if self.config.pl_path_gain_state:
                fs_inverted = [element * -1 for element in self.fs_y]
                self.pl_fs_line.setData(self.pl_points, fs_inverted)
            else:
                self.pl_fs_line.setData(self.pl_points, self.fs_y)
        else:
            self.pl_fs_line.clear()

        if self.pl_tworay_checkbox.isChecked():
            self.two_ray_model = md.TwoRayModel(ref_pl=self.config.pl_ref_pl_value,
                    pl_exp=self.config.pl_exp_tworay_value,
                    ref_dist=self.config.pl_ref_dist_value)
            self.two_ray_y = self.two_ray_model.path_loss_array(self.pl_points) - self.config.pl_tx_gain_value - self.config.pl_rx_gain_value
            if self.config.pl_path_gain_state:
                two_ray_inverted = [element * -1 for element in self.two_ray_y]
                self.pl_tworay_line.setData(self.pl_points, two_ray_inverted) 
            else:
                self.pl_tworay_line.setData(self.pl_points, self.two_ray_y)
        else:
            self.pl_tworay_line.clear()

        if self.pl_ci_checkbox.isChecked():
            self.ci_model = md.CIModel(freq=self.config.pl_freq_value,
                    pl_exp=self.config.pl_exp_value, sigma=self.config.pl_sigma_value,
                    ref_dist=self.config.pl_ref_dist_value)
            self.ci_y = self.ci_model.path_loss_array(self.pl_points) - self.config.pl_tx_gain_value - self.config.pl_rx_gain_value
            if self.config.pl_path_gain_state:
                ci_inverted = [element * -1 for element in self.ci_y]
                self.pl_ci_line.setData(self.pl_points, ci_inverted)
            else:
                self.pl_ci_line.setData(self.pl_points, self.ci_y)
        else:
            self.pl_ci_line.clear()

        if self.pl_abg_checkbox.isChecked():
            self.abg_model = md.ABGModel(freq=self.config.pl_freq_value,
                    alpha=self.config.pl_alpha_value, beta=self.config.pl_beta_value,
                    gamma=self.config.pl_gamma_value, sigma=self.config.pl_sigma_value,
                    ref_dist=self.config.pl_ref_dist_value)
            self.abg_y = self.abg_model.path_loss_array(self.pl_points) - self.config.pl_tx_gain_value - self.config.pl_rx_gain_value
            if self.config.pl_path_gain_state:
                abg_inverted = [element * -1 for element in self.abg_y]
                self.pl_abg_line.setData(self.pl_points, abg_inverted)
            else:
                self.pl_abg_line.setData(self.pl_points, self.abg_y)
        else:
            self.pl_abg_line.clear()

        if self.pl_oh_u_checkbox.isChecked():
            self.ohu_model = md.OHUrbanModel(freq=self.config.pl_freq_value,
                    bs_height=self.config.pl_bs_height_value,
                    ue_height=self.config.pl_ue_height_value,
                    large_city=self.config.pl_large_city_state)
            self.pl_oh_u_y = self.ohu_model.path_loss_array(self.pl_points) - self.config.pl_tx_gain_value - self.config.pl_rx_gain_value
            if self.config.pl_path_gain_state:
                oh_u_inverted = [element * -1 for element in self.pl_oh_u_y]
                self.pl_oh_u_line.setData(self.pl_points, oh_u_inverted)
            else:
                self.pl_oh_u_line.setData(self.pl_points, self.pl_oh_u_y)
        else:
            self.pl_oh_u_line.clear()

        if self.pl_oh_s_checkbox.isChecked():
            self.ohs_model = md.OHSuburbanModel(freq=self.config.pl_freq_value,
                    bs_height=self.config.pl_bs_height_value,
                    ue_height=self.config.pl_ue_height_value,
                    large_city=self.config.pl_large_city_state)
            self.pl_oh_s_y = self.ohs_model.path_loss_array(self.pl_points) - self.config.pl_tx_gain_value - self.config.pl_rx_gain_value
            if self.config.pl_path_gain_state:
                oh_s_inverted = [element * -1 for element in self.pl_oh_s_y]
                self.pl_oh_s_line.setData(self.pl_points, oh_s_inverted)
            else:
                self.pl_oh_s_line.setData(self.pl_points, self.pl_oh_s_y)
        else:
            self.pl_oh_s_line.clear()

        if self.pl_oh_r_checkbox.isChecked():
            self.ohr_model = md.OHRuralModel(freq=self.config.pl_freq_value,
                    bs_height=self.config.pl_bs_height_value,
                    ue_height=self.config.pl_ue_height_value,
                    large_city=self.config.pl_large_city_state)
            self.pl_oh_r_y = self.ohr_model.path_loss_array(self.pl_points) - self.config.pl_tx_gain_value - self.config.pl_rx_gain_value
            if self.config.pl_path_gain_state:
                oh_r_inverted = [element * -1 for element in self.pl_oh_r_y]
                self.pl_oh_r_line.setData(self.pl_points, oh_r_inverted)
            else:
                self.pl_oh_r_line.setData(self.pl_points, self.pl_oh_r_y)
        else:
            self.pl_oh_r_line.clear()

def main():
    app = QtWidgets.QApplication(sys.argv)
    w = WSWindow()
    w.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
