#!/usr/bin/python3

from PyQt5 import QtWidgets, QtCore, QtGui
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from pathlib import Path
import sys  # We need sys so that we can pass argv to QApplication
import os
import time
import yaml
import numpy as np
from random import randint
import walksignal.dataset as ds
import walksignal.models as md
import walksignal.plottools as pt
import walksignal.utils as utils
import walksignal.bitrate as br

class WSWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super(WSWindow, self).__init__(*args, **kwargs)

        self.setWindowTitle("walksignal 0.4.0")
        if os.path.isfile("./lastcfg.yaml"):
            self.config = utils.Config("lastcfg.yaml")
            self.configdata = self.config.load()
        else:
            self.configdata = None

        if self.configdata is not None:
            self.signal_data_file = self.configdata.get("signal_data_file")
            self.bitrate_data_file = self.configdata.get("bitrate_data_file")
            self.tower_lat = self.configdata.get("tower_lat")
            self.tower_lon = self.configdata.get("tower_lon")
        else:
            self.signal_data_file = None
            self.bitrate_data_file = None
            self.tower_lat = None
            self.tower_lon = None

        self.write_config = None
        self.signal_dataset = None
        self.x_range = None
        self.y_range = None
        self.bitrate_dataset = None

        self.cell = None
        self.cell_pl = None
        self.cell_distances = None
        self.tower = None
        self.cbar = None
        self.map_canvas = pt.MplCanvas(self, width=5, height=4, dpi=100)
        self.map_toolbar = NavigationToolbar(self.map_canvas, self)

        self.br_distances = None

        self.pl_points = np.arange(0.5, 2500, 0.5)
        self.pl_freq = 50
        self.pl_alpha = 1
        self.pl_beta = 1
        self.pl_gamma = 1
        self.pl_sigma = 1
        self.pl_exp = 1
        self.pl_ref_dist = 1
        self.pl_ref_freq = 1000000000
        self.pl_fs_y = None
        self.pl_tx_power = 43
        self.pl_tx_gain = 3
        self.pl_rx_gain = 3
        self.pl_bs_height = 1
        self.pl_ue_height = 1
        self.pl_correction_factor = 1
        self.pl_large_city = True
        self.pl_path_gain = False

        self.pl_red_pen = pg.mkPen(color=(255, 0, 0))
        self.pl_green_pen = pg.mkPen(color=(64, 192, 64))
        self.pl_blue_pen = pg.mkPen(color=(0, 0, 255))
        self.pl_green_pen = pg.mkPen(color=(64,192,64))
        self.pl_black_pen = pg.mkPen(color=(0, 0, 0))
        self.pl_orange_pen = pg.mkPen(color=(255, 145, 0))
        self.pl_oh_u_pen = pg.mkPen(color=(0, 255, 0))
        self.pl_oh_s_pen = pg.mkPen(color=(192,64,192))
        self.pl_oh_r_pen = pg.mkPen(color=(64, 64, 144))

        self.x = list(range(100))  # 100 time points
        self.y = [randint(0,100) for _ in range(100)]  # 100 data points

        self.setupUI()
    
    def closeEvent(self, event):
        self.setConfig()
        self.saveConfig()

    def setupUI(self):
        self.setupPlotWidgets()
        self.setupLines()
        self.setupFileControls()
        self.setupCellControls()
        self.setupPathLossControls()
        self.setupPlotTabs()
        self.setupControlTabs()
        self.setupControlsSidebar()
        self.setupDataSidebar()

        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.addWidget(self.dataSidebarWidget, 1)
        self.main_layout.addWidget(self.plot_tabs, 3)
        self.main_layout.addWidget(self.plotSidebarWidget, 1)
        self.br_widget = QtWidgets.QWidget()
        self.br_widget.setLayout(self.main_layout)
        self.setCentralWidget(self.br_widget)
        if self.signal_data_file and self.bitrate_data_file:
            self.setDataSource()
            self.loadCell()
            self.set_signal_data_text.setText(' '.join(self.signal_data_file))
            self.set_bitrate_data_text.setText(' '.join(self.bitrate_data_file))


    def setupPlotWidgets(self):
        self.br_widget = pg.PlotWidget()
        self.br_widget.addLegend()
        self.br_widget.setBackground('w')
        self.br_widget.showGrid(x=True, y=True, alpha=0.5)
        self.br_widget.setYRange(0, 250)

        self.pl_widget = pg.PlotWidget()
        self.pl_widget.addLegend()
        self.pl_widget.setBackground('w')
        self.pl_widget.showGrid(x=True, y=True, alpha=0.5)
        self.pl_widget.setYRange(-150, 150)

    def setupLines(self):
        self.styles = {'color':'b', 'font-size':'18px'}
        self.br_widget.setLabel('left', "Bitrate (Mb/s)", **self.styles)
        self.br_widget.setLabel('bottom', "Distance (m)", **self.styles)

        self.pl_abg_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_blue_pen, name="ABG Model")
        self.pl_ci_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_green_pen, name="CI Model")
        self.pl_fs_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_black_pen, name="Free Space Model")
        self.pl_comp_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_orange_pen, name="Composite Model")
        self.pl_oh_u_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_oh_u_pen, name="Okumura-Hata Urban")
        self.pl_oh_s_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_oh_s_pen, name="Okumura-Hata Suburban")
        self.pl_oh_r_line = self.pl_widget.plot(self.x, self.y, pen=self.pl_oh_r_pen, name="Okumura-Hata Rural")
        self.pl_measured_line = self.pl_widget.plot(self.x, self.y, pen=None, symbol="o", symbolPen=self.pl_red_pen, symbolSize=3, symbolBrush=(255, 0, 0, 255), name="Measured")

        self.br_up_line = self.br_widget.plot(self.x, self.y, pen=None, symbol="o", symbolPen=self.pl_blue_pen, symbolSize=5, symbolBrush=(0, 0, 255, 255), name="Upload")
        self.br_down_line = self.br_widget.plot(self.x, self.y, pen=None, symbol="o", symbolPen=self.pl_red_pen, symbolSize=5, symbolBrush=(255, 0, 0, 255), name="Download")

        self.styles = {'color':'b', 'font-size':'18px'}
        self.pl_widget.setLabel('left', "Path Loss (dB)", **self.styles)
        self.pl_widget.setLabel('bottom', "Distance (m)", **self.styles)

    def setupFileControls(self):
        self.file_control_box = QtWidgets.QVBoxLayout()
        self.load_box = QtWidgets.QVBoxLayout()
        self.set_signal_data_box = QtWidgets.QVBoxLayout()
        self.set_bitrate_data_box = QtWidgets.QVBoxLayout()

        self.file_controls_title = QtWidgets.QLabel('File Selection', self)
        self.file_controls_title.setFont(QtGui.QFont('Arial', 16))

        self.signal_data_section_title = QtWidgets.QLabel("Signal Data", self)
        self.signal_data_section_title.setFont(QtGui.QFont('Arial', 14))
        self.set_signal_data_button = QtWidgets.QPushButton('Set Signal Data', self)
        self.set_signal_data_button.clicked.connect(self.showSignalFileDialog)
        self.set_signal_data_text = QtWidgets.QLineEdit('None', self)
        self.set_signal_data_text.setReadOnly(True)

        self.bitrate_data_section_title = QtWidgets.QLabel("Bitrate Data", self)
        self.bitrate_data_section_title.setFont(QtGui.QFont('Arial', 14))
        self.set_bitrate_data_button = QtWidgets.QPushButton('Set Bitrate Data', self)
        self.set_bitrate_data_button.clicked.connect(self.showBitrateFileDialog)
        self.set_bitrate_data_text = QtWidgets.QLineEdit('None', self)
        self.set_bitrate_data_text.setReadOnly(True)

        self.load_button = QtWidgets.QPushButton('Load', self)
        self.load_button.clicked.connect(self.setDataSource)

        self.load_box.addWidget(self.load_button)
        self.set_signal_data_box.addWidget(self.set_signal_data_button)
        self.set_signal_data_box.addWidget(self.set_signal_data_text)
        self.set_bitrate_data_box.addWidget(self.set_bitrate_data_button)
        self.set_bitrate_data_box.addWidget(self.set_bitrate_data_text)
        self.file_control_box.addWidget(self.file_controls_title)
        self.file_control_box.addWidget(self.signal_data_section_title)
        self.file_control_box.addLayout(self.set_signal_data_box)
        self.file_control_box.addWidget(self.bitrate_data_section_title)
        self.file_control_box.addLayout(self.set_bitrate_data_box)
        self.file_control_box.addLayout(self.load_box)

    def setupPathLossControls(self):
        self.pl_box = QtWidgets.QVBoxLayout()
        self.br_box = QtWidgets.QVBoxLayout()
        self.pl_checkbox_title_box = QtWidgets.QHBoxLayout()
        self.pl_checkbox_box = QtWidgets.QVBoxLayout()
        self.pl_pl_title_box = QtWidgets.QHBoxLayout()
        self.pl_th_title_box = QtWidgets.QHBoxLayout()
        self.pl_checkbox_subbox_1 = QtWidgets.QHBoxLayout()
        self.pl_oh_title_box = QtWidgets.QHBoxLayout()
        self.pl_checkbox_subbox_2 = QtWidgets.QHBoxLayout()
        self.pl_checkbox_subbox_3 = QtWidgets.QHBoxLayout()
        self.pl_freq_box = QtWidgets.QHBoxLayout()
        self.pl_alpha_box = QtWidgets.QHBoxLayout()
        self.pl_beta_box = QtWidgets.QHBoxLayout()
        self.pl_gamma_box = QtWidgets.QHBoxLayout()
        self.pl_sigma_box = QtWidgets.QHBoxLayout()
        self.pl_exp_box = QtWidgets.QHBoxLayout()
        self.pl_tx_power_box = QtWidgets.QHBoxLayout()
        self.pl_tx_gain_box = QtWidgets.QHBoxLayout()
        self.pl_rx_gain_box = QtWidgets.QHBoxLayout()
        self.pl_ref_dist_box = QtWidgets.QHBoxLayout()
        self.pl_ref_freq_box = QtWidgets.QHBoxLayout()
        self.pl_bs_height_box = QtWidgets.QHBoxLayout()
        self.pl_ue_height_box = QtWidgets.QHBoxLayout()

        self.setupPLCheckBoxes()
        self.setupPLSliders()
        self.setupPLTextBoxes()
        self.setupPLTitles()
        self.setupLatLonBoxes()

        self.pl_box.addLayout(self.pl_checkbox_title_box)
        self.pl_box.addLayout(self.pl_th_title_box)
        self.pl_checkbox_box.addLayout(self.pl_checkbox_subbox_1)
        self.pl_checkbox_box.addLayout(self.pl_oh_title_box)
        self.pl_checkbox_box.addLayout(self.pl_checkbox_subbox_2)
        self.pl_checkbox_box.addLayout(self.pl_checkbox_subbox_3)
        self.pl_box.addLayout(self.pl_checkbox_box)
        self.pl_box.addLayout(self.pl_freq_box)
        self.pl_box.addLayout(self.pl_ref_dist_box)
        self.pl_box.addLayout(self.pl_ref_freq_box)
        self.pl_box.addLayout(self.pl_alpha_box)
        self.pl_box.addLayout(self.pl_beta_box)
        self.pl_box.addLayout(self.pl_gamma_box)
        self.pl_box.addLayout(self.pl_sigma_box)
        self.pl_box.addLayout(self.pl_exp_box)
        self.pl_box.addLayout(self.pl_tx_gain_box)
        self.pl_box.addLayout(self.pl_rx_gain_box)
        self.pl_box.addLayout(self.pl_tx_power_box)
        self.pl_box.addLayout(self.pl_bs_height_box)
        self.pl_box.addLayout(self.pl_ue_height_box)
        self.pl_box.setAlignment(QtCore.Qt.AlignTop)

    def setupBitrateControls(self):
        self.bitrate_box = QtWidgets.QVBoxLayout()
        self.bitrate_title = QtWidgets.QLabel("Bitrate Controls", self)
        self.bitrate_title.setFont(QtGui.QFont("Arial", 14))

    def setupCellControls(self):
        self.tower_box = QtWidgets.QVBoxLayout()
        self.cellid_box = QtWidgets.QHBoxLayout()
        self.mcc_box = QtWidgets.QHBoxLayout()
        self.mnc_box = QtWidgets.QHBoxLayout()
        self.lac_box = QtWidgets.QHBoxLayout()
        self.latbox = QtWidgets.QHBoxLayout()
        self.lonbox = QtWidgets.QHBoxLayout()
        self.set_tower_box = QtWidgets.QHBoxLayout()

        self.tower_combo_title = QtWidgets.QLabel('Cell Selection', self)
        self.tower_combo_title.setFont(QtGui.QFont('Arial', 14))

        self.cellid_label = QtWidgets.QLabel('Cell IDs', self)
        self.mcc_label = QtWidgets.QLabel('MCCs', self)
        self.mnc_label = QtWidgets.QLabel('MNCs', self)
        self.lac_label = QtWidgets.QLabel('LACs', self)

        self.cellid_count = QtWidgets.QLabel('', self)
        self.mcc_count = QtWidgets.QLabel('', self)
        self.mnc_count = QtWidgets.QLabel('', self)
        self.lac_count = QtWidgets.QLabel('', self)

        self.cellid_combo = QtWidgets.QComboBox(self)
        self.mcc_combo = QtWidgets.QComboBox(self)
        self.mnc_combo = QtWidgets.QComboBox(self)
        self.lac_combo = QtWidgets.QComboBox(self)

        self.cellid_combo.activated.connect(self.setCell)

        self.cellid_box.addWidget(self.cellid_label)
        self.cellid_box.addWidget(self.cellid_count)
        self.cellid_box.addWidget(self.cellid_combo)
        self.mcc_box.addWidget(self.mcc_label)
        self.mcc_box.addWidget(self.mcc_count)
        self.mcc_box.addWidget(self.mcc_combo)
        self.mnc_box.addWidget(self.mnc_label)
        self.mnc_box.addWidget(self.mnc_count)
        self.mnc_box.addWidget(self.mnc_combo)
        self.lac_box.addWidget(self.lac_label)
        self.lac_box.addWidget(self.lac_count)
        self.lac_box.addWidget(self.lac_combo)
        self.cell_load_button = QtWidgets.QPushButton('Load Cell Data', self)
        self.cell_load_button.clicked.connect(self.loadCell)
        
        self.tower_box.addWidget(self.tower_combo_title)
        self.tower_box.addLayout(self.cellid_box)
        self.tower_box.addLayout(self.mcc_box)
        self.tower_box.addLayout(self.mnc_box)
        self.tower_box.addLayout(self.lac_box)
        self.tower_box.addWidget(self.cell_load_button)
        self.tower_box.addLayout(self.latbox)
        self.tower_box.addLayout(self.lonbox)
        self.tower_box.addLayout(self.set_tower_box)
        self.tower_box.setAlignment(QtCore.Qt.AlignTop)

    def setupPlotTabs(self):
        self.plot_tabs = QtWidgets.QTabWidget()
        self.map_box = QtWidgets.QVBoxLayout()
        self.map_box.addWidget(self.map_toolbar)
        self.map_box.addWidget(self.map_canvas)
        self.plot_tab1 = QtWidgets.QWidget()
        self.plot_tab1.setLayout(self.map_box)
        self.plot_tab2 = self.pl_widget
        self.plot_tab3 = self.br_widget
        self.plot_tabs.resize(300, 200)
        self.plot_tabs.addTab(self.plot_tab1, "Cell Map")
        self.plot_tabs.addTab(self.plot_tab2, "Path Loss")
        self.plot_tabs.addTab(self.plot_tab3, "Bitrate")

    def setupControlTabs(self):
        self.control_tabs = QtWidgets.QTabWidget()
        self.pl_control_tab = QtWidgets.QWidget()
        self.br_control_tab = QtWidgets.QWidget()
        self.control_tabs.addTab(self.pl_control_tab, "Path Loss")
        self.control_tabs.addTab(self.br_control_tab, "Bitrate")

    def setupControlsSidebar(self):
        self.plotSidebar = QtWidgets.QVBoxLayout()
        self.pl_control_tab.setLayout(self.pl_box)
        self.br_control_tab.setLayout(self.br_box)

        self.controls_title = QtWidgets.QLabel('Controls', self)
        self.controls_title.setFont(QtGui.QFont('Arial', 14))

        self.plotSidebar.addWidget(self.controls_title)
        self.plotSidebar.addWidget(self.control_tabs)
        self.plotSidebar.setAlignment(QtCore.Qt.AlignTop)
        self.plotSidebarWidget = QtWidgets.QWidget()
        self.plotSidebarWidget.setLayout(self.plotSidebar)

    def setupDataSidebar(self):
        self.dataSidebar = QtWidgets.QVBoxLayout()
        self.dataSidebar.addLayout(self.file_control_box)
        self.dataSidebar.addLayout(self.tower_box)
        self.dataSidebar.addWidget(self.cell_load_button)
        self.dataSidebar.setAlignment(QtCore.Qt.AlignTop)
        self.dataSidebarWidget = QtWidgets.QWidget()
        self.dataSidebarWidget.setLayout(self.dataSidebar)

    def setupPLCheckBoxes(self):
        self.pl_fs_checkbox = QtWidgets.QCheckBox("FS")
        self.pl_fs_checkbox.setChecked(True)
        self.pl_fs_checkbox.stateChanged.connect(self.plCheckboxUpdate)
        self.pl_checkbox_subbox_1.addWidget(self.pl_fs_checkbox)

        self.pl_comp_checkbox = QtWidgets.QCheckBox("Comp")
        self.pl_comp_checkbox.setChecked(True)
        self.pl_comp_checkbox.stateChanged.connect(self.plCheckboxUpdate)
        self.pl_checkbox_subbox_1.addWidget(self.pl_comp_checkbox)

        self.pl_abg_checkbox = QtWidgets.QCheckBox("ABG")
        self.pl_abg_checkbox.setChecked(True)
        self.pl_abg_checkbox.stateChanged.connect(self.plCheckboxUpdate)
        self.pl_checkbox_subbox_1.addWidget(self.pl_abg_checkbox)

        self.pl_ci_checkbox = QtWidgets.QCheckBox("CI")
        self.pl_ci_checkbox.setChecked(False)
        self.pl_ci_checkbox.stateChanged.connect(self.plCheckboxUpdate)
        self.pl_checkbox_subbox_1.addWidget(self.pl_ci_checkbox)

        self.pl_oh_u_checkbox = QtWidgets.QCheckBox("Urban")
        self.pl_oh_u_checkbox.setChecked(False)
        self.pl_oh_u_checkbox.stateChanged.connect(self.plCheckboxUpdate)
        self.pl_checkbox_subbox_2.addWidget(self.pl_oh_u_checkbox)

        self.pl_oh_s_checkbox = QtWidgets.QCheckBox("Suburban")
        self.pl_oh_s_checkbox.setChecked(False)
        self.pl_oh_s_checkbox.stateChanged.connect(self.plCheckboxUpdate)
        self.pl_checkbox_subbox_2.addWidget(self.pl_oh_s_checkbox)

        self.pl_oh_r_checkbox = QtWidgets.QCheckBox("Rural")
        self.pl_oh_r_checkbox.setChecked(False)
        self.pl_oh_r_checkbox.stateChanged.connect(self.plCheckboxUpdate)
        self.pl_checkbox_subbox_2.addWidget(self.pl_oh_r_checkbox)

        self.pl_large_city_checkbox = QtWidgets.QCheckBox("Large City")
        self.pl_large_city_checkbox.setChecked(True)
        self.pl_large_city_checkbox.stateChanged.connect(self.plCheckboxUpdate)
        self.pl_checkbox_subbox_3.addWidget(self.pl_large_city_checkbox)

        self.pl_path_gain_checkbox = QtWidgets.QCheckBox("Plot as Gain")
        self.pl_path_gain_checkbox.setChecked(False)
        self.pl_path_gain_checkbox.stateChanged.connect(self.plCheckboxUpdate)
        self.pl_checkbox_subbox_3.addWidget(self.pl_path_gain_checkbox)

    def setupPLSliders(self):
        self.pl_alpha_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_alpha_slider.setRange(0, 100)
        self.pl_alpha_slider.setValue(10)
        self.pl_alpha_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_alpha_slider_label = QtWidgets.QLabel('Alpha', self)
        self.pl_alpha_value_label = QtWidgets.QLabel('1', self)
        self.pl_alpha_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_alpha_box.addWidget(self.pl_alpha_slider_label)
        self.pl_alpha_box.addWidget(self.pl_alpha_slider)
        self.pl_alpha_box.addWidget(self.pl_alpha_value_label)

        self.pl_beta_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_beta_slider.setRange(-1000, 1000)
        self.pl_beta_slider.setValue(0)
        self.pl_beta_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_beta_slider_label = QtWidgets.QLabel('Beta', self)
        self.pl_beta_value_label = QtWidgets.QLabel('0 dB', self)
        self.pl_beta_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_beta_box.addWidget(self.pl_beta_slider_label)
        self.pl_beta_box.addWidget(self.pl_beta_slider)
        self.pl_beta_box.addWidget(self.pl_beta_value_label)

        self.pl_gamma_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_gamma_slider.setRange(0, 100)
        self.pl_gamma_slider.setValue(10)
        self.pl_gamma_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_gamma_slider_label = QtWidgets.QLabel('Gamma', self)
        self.pl_gamma_value_label = QtWidgets.QLabel('1', self)
        self.pl_gamma_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_gamma_box.addWidget(self.pl_gamma_slider_label)
        self.pl_gamma_box.addWidget(self.pl_gamma_slider)
        self.pl_gamma_box.addWidget(self.pl_gamma_value_label)

        self.pl_sigma_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_sigma_slider.setRange(0, 100)
        self.pl_sigma_slider.setValue(10)
        self.pl_sigma_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_sigma_slider_label = QtWidgets.QLabel('Sigma', self)
        self.pl_sigma_value_label = QtWidgets.QLabel('1 dB', self)
        self.pl_sigma_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_sigma_box.addWidget(self.pl_sigma_slider_label)
        self.pl_sigma_box.addWidget(self.pl_sigma_slider)
        self.pl_sigma_box.addWidget(self.pl_sigma_value_label)

        self.pl_exp_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_exp_slider.setRange(0, 100)
        self.pl_exp_slider.setValue(10)
        self.pl_exp_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_exp_slider_label = QtWidgets.QLabel('PL Exp', self)
        self.pl_exp_value_label = QtWidgets.QLabel('1', self)
        self.pl_exp_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_exp_box.addWidget(self.pl_exp_slider_label)
        self.pl_exp_box.addWidget(self.pl_exp_slider)
        self.pl_exp_box.addWidget(self.pl_exp_value_label)

        self.pl_tx_power_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_tx_power_slider.setRange(0, 1000)
        self.pl_tx_power_slider.setValue(430)
        self.pl_tx_power_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_tx_power_slider_label = QtWidgets.QLabel('TX Power', self)
        self.pl_tx_power_value_label = QtWidgets.QLabel('43 dBm', self)
        self.pl_tx_power_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_tx_power_box.addWidget(self.pl_tx_power_slider_label)
        self.pl_tx_power_box.addWidget(self.pl_tx_power_slider)
        self.pl_tx_power_box.addWidget(self.pl_tx_power_value_label)

        self.pl_tx_gain_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_tx_gain_slider.setRange(0, 1000)
        self.pl_tx_gain_slider.setValue(0)
        self.pl_tx_gain_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_tx_gain_slider_label = QtWidgets.QLabel('TX Gain', self)
        self.pl_tx_gain_value_label = QtWidgets.QLabel('3 dB', self)
        self.pl_tx_gain_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_tx_gain_box.addWidget(self.pl_tx_gain_slider_label)
        self.pl_tx_gain_box.addWidget(self.pl_tx_gain_slider)
        self.pl_tx_gain_box.addWidget(self.pl_tx_gain_value_label)

        self.pl_rx_gain_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_rx_gain_slider.setRange(0, 200)
        self.pl_rx_gain_slider.setValue(0)
        self.pl_rx_gain_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_rx_gain_slider_label = QtWidgets.QLabel('RX Gain', self)
        self.pl_rx_gain_value_label = QtWidgets.QLabel('3 dB', self)
        self.pl_rx_gain_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_rx_gain_box.addWidget(self.pl_rx_gain_slider_label)
        self.pl_rx_gain_box.addWidget(self.pl_rx_gain_slider)
        self.pl_rx_gain_box.addWidget(self.pl_rx_gain_value_label)

        self.pl_bs_height_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_bs_height_slider.setRange(0, 2500)
        self.pl_bs_height_slider.setValue(10)
        self.pl_bs_height_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_bs_height_slider_label = QtWidgets.QLabel('BS Height', self)
        self.pl_bs_height_value_label = QtWidgets.QLabel('1 m', self)
        self.pl_bs_height_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_bs_height_box.addWidget(self.pl_bs_height_slider_label)
        self.pl_bs_height_box.addWidget(self.pl_bs_height_slider)
        self.pl_bs_height_box.addWidget(self.pl_bs_height_value_label)

        self.pl_ue_height_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self)
        self.pl_ue_height_slider.setRange(0, 100)
        self.pl_ue_height_slider.setValue(10)
        self.pl_ue_height_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pl_ue_height_slider_label = QtWidgets.QLabel('UE Height', self)
        self.pl_ue_height_value_label = QtWidgets.QLabel('1 m', self)
        self.pl_ue_height_slider.valueChanged[int].connect(self.plSliderUpdate)
        self.pl_ue_height_box.addWidget(self.pl_ue_height_slider_label)
        self.pl_ue_height_box.addWidget(self.pl_ue_height_slider)
        self.pl_ue_height_box.addWidget(self.pl_ue_height_value_label)

    def setupPLTextBoxes(self):
        self.pl_freq_textbox = QtWidgets.QLineEdit(self)
        self.pl_freq_textbox.setText("50")
        self.pl_freq_textbox_label = QtWidgets.QLabel('Frequency', self)
        self.pl_freq_value_label = QtWidgets.QLabel('MHz', self)
        self.pl_freq_textbox.textEdited.connect(self.plTextboxUpdate)
        self.pl_freq_box.addWidget(self.pl_freq_textbox_label)
        self.pl_freq_box.addWidget(self.pl_freq_textbox)
        self.pl_freq_box.addWidget(self.pl_freq_value_label)

        self.pl_ref_dist_textbox = QtWidgets.QLineEdit(self)
        self.pl_ref_dist_textbox.setText("1")
        self.pl_ref_dist_textbox_label = QtWidgets.QLabel('Ref Dist', self)
        self.pl_ref_dist_value_label = QtWidgets.QLabel('m', self)
        self.pl_ref_dist_textbox.textEdited.connect(self.plTextboxUpdate)
        self.pl_ref_dist_box.addWidget(self.pl_ref_dist_textbox_label)
        self.pl_ref_dist_box.addWidget(self.pl_ref_dist_textbox)
        self.pl_ref_dist_box.addWidget(self.pl_ref_dist_value_label)

        self.pl_ref_freq_textbox = QtWidgets.QLineEdit(self)
        self.pl_ref_freq_textbox.setText("1000")
        self.pl_ref_freq_textbox_label = QtWidgets.QLabel('Ref Freq', self)
        self.pl_ref_freq_value_label = QtWidgets.QLabel('MHz', self)
        self.pl_ref_freq_textbox.textEdited.connect(self.plTextboxUpdate)
        self.pl_ref_freq_box.addWidget(self.pl_ref_freq_textbox_label)
        self.pl_ref_freq_box.addWidget(self.pl_ref_freq_textbox)
        self.pl_ref_freq_box.addWidget(self.pl_ref_freq_value_label)

    def setupPLTitles(self):
        self.pl_checkbox_title = QtWidgets.QLabel("Models")
        self.pl_checkbox_title.setFont(QtGui.QFont("Arial", 12))
        self.pl_checkbox_title_box.addWidget(self.pl_checkbox_title)

        self.pl_th_title = QtWidgets.QLabel("Large-Scale")
        self.pl_th_title.setFont(QtGui.QFont("Arial", 10))
        self.pl_th_title_box.addWidget(self.pl_th_title)

        self.pl_oh_title = QtWidgets.QLabel("Okumura-Hata")
        self.pl_oh_title.setFont(QtGui.QFont("Arial", 10))
        self.pl_oh_title_box.addWidget(self.pl_oh_title)

    def setupLatLonBoxes(self):
        self.lat_edit = QtWidgets.QLineEdit(self)
        if self.tower_lat:
            self.lat_edit.setText(str(self.tower_lat))
        self.latbox_label = QtWidgets.QLabel("Tower Lat", self)
        self.latbox.addWidget(self.latbox_label)
        self.latbox.addWidget(self.lat_edit)
        self.lon_edit = QtWidgets.QLineEdit(self)
        if self.tower_lon:
            self.lon_edit.setText(str(self.tower_lon))
        self.lonbox_label = QtWidgets.QLabel("Tower Lon", self)
        self.lonbox.addWidget(self.lonbox_label)
        self.lonbox.addWidget(self.lon_edit)

        self.set_tower_button = QtWidgets.QPushButton('Set Tower', self)
        self.set_tower_button.clicked.connect(self.setTowerLocation)
        self.set_tower_box.addWidget(self.set_tower_button)

    def showSignalFileDialog(self):
        home_dir = str(Path.home)
        fname = QtWidgets.QFileDialog.getOpenFileNames(self, 'Open file', home_dir)

        if fname[0]:
            print("Selected signal signal_data_file {0}".format(fname[0]))
            self.signal_data_file = fname[0]
            self.set_signal_data_text.setText(str(self.signal_data_file))

    def showBitrateFileDialog(self):
        home_dir = str(Path.home)
        fname = QtWidgets.QFileDialog.getOpenFileNames(self, 'Open file', home_dir)

        if fname[0]:
            print("Selected bitrate signal_data_file {0}".format(fname[0]))
            self.bitrate_data_file = fname[0]
            self.set_bitrate_data_text.setText(str(self.bitrate_data_file))

    def setDataSource(self):
        if self.signal_data_file:
            print("Loading data...")
            self.start_time = time.time()
            self.signal_dataset = ds.DataSet(self.signal_data_file)
            self.duration = time.time() - self.start_time
            print("Done loading data in {:.2f} seconds".format(self.duration))
            self.cellid_combo.clear()
            self.mcc_combo.clear()
            self.mnc_combo.clear()
            self.lac_combo.clear()
            self.cellid_count.setText("(" + str(len(self.signal_dataset.cellid_u)) + ")")
            self.mcc_count.setText("(" + str(len(self.signal_dataset.mcc_u)) + ")")
            self.mnc_count.setText("(" + str(len(self.signal_dataset.mnc_u)) + ")")
            self.lac_count.setText("(" + str(len(self.signal_dataset.lac_u)) + ")")

            for mcc in self.signal_dataset.mcc_u:
                self.mcc_combo.addItem(str(mcc))
            for mnc in self.signal_dataset.mnc_u:
                self.mnc_combo.addItem(str(mnc))
            for lac in self.signal_dataset.lac_u:
                self.lac_combo.addItem(str(lac))
            for cellid in self.signal_dataset.cellid_u:
                self.cellid_combo.addItem(str(cellid))
        else:
            print("No data files selected")

        if self.bitrate_data_file:
            self.bitrate_dataset = br.BitRateSet(self.bitrate_data_file)
        else:
            print("No bitrate file selected")

    def loadCell(self):
        print("Loading cell data...")
        self.setCell()
        self.updateCellMap()
        self.setTowerLocation()
        self.setConfig()

    def setCell(self):
        self.cell = self.signal_dataset.get_cell(self.cellid_combo.currentText())
        point_count = len(self.cell.signal_power)
        self.cell_load_button.setText("Load Cell Data ({0} points)".format(point_count))

    def setConfig(self):
        self.write_config = {
                'signal_data_file': self.signal_data_file,
                'bitrate_data_file': self.bitrate_data_file,
        }
        if self.tower_lat and self.tower_lon:
            self.write_config['tower_lat'] = self.tower_lat
            self.write_config['tower_lon'] = self.tower_lon

    def setTowerLocation(self):
        if self.lat_edit.text() and self.lon_edit.text():
            self.tower_lat = float(self.lat_edit.text())
            self.tower_lon = float(self.lon_edit.text())
            self.map_canvas.axes.scatter(float(self.tower_lon), float(self.tower_lat), zorder=1, alpha=1.0, s=20, color="blue")
            self.map_canvas.draw()
            self.cell_distances = self.cell.get_distances(self.tower_lat, self.tower_lon)
            self.cell_pl = self.cell.get_path_loss(self.pl_tx_power)
            self.plUpdatePlot()
            self.brUpdatePlot()
        else:
            print("Can't draw tower, bad lat/lon")

    def saveConfig(self):
        self.config.save(self.write_config)

    def plTextboxUpdate(self):
        self.pl_freq = float(self.pl_freq_textbox.text())
        self.pl_ref_dist = float(self.pl_ref_dist_textbox.text())
        self.pl_ref_freq = float(self.pl_ref_freq_textbox.text())
        if self.signal_dataset:
            self.plUpdatePlot()
    
    def plCheckboxUpdate(self):
        if self.pl_large_city_checkbox.isChecked():
            self.pl_large_city = True
        else:
            self.pl_large_city = False

        if self.pl_path_gain_checkbox.isChecked():
            self.pl_path_gain = True
            self.pl_widget.setLabel('left', "Path Gain (dB)", **self.styles)
        else:
            self.pl_path_gain = False
            self.pl_widget.setLabel('left', "Path Loss (dB)", **self.styles)
        self.plUpdatePlot()

    def plSliderUpdate(self):
        self.pl_alpha = self.pl_alpha_slider.value() / 10.0
        self.pl_beta = self.pl_beta_slider.value() / 10.0
        self.pl_gamma = self.pl_gamma_slider.value() / 10.0
        self.pl_sigma = self.pl_sigma_slider.value() / 10.0
        self.pl_exp = self.pl_exp_slider.value() / 10.0
        self.pl_tx_power = self.pl_tx_power_slider.value() / 10.0
        self.pl_tx_gain = self.pl_tx_gain_slider.value() / 10.0
        self.pl_rx_gain = self.pl_rx_gain_slider.value() / 10.0
        self.pl_bs_height = self.pl_bs_height_slider.value() / 10.0
        self.pl_ue_height = self.pl_ue_height_slider.value() / 10.0
        self.pl_alpha_value_label.setText(str(self.pl_alpha))
        self.pl_beta_value_label.setText(str(self.pl_beta) + " dB")
        self.pl_gamma_value_label.setText(str(self.pl_gamma))
        self.pl_sigma_value_label.setText(str(self.pl_sigma) + " dB")
        self.pl_exp_value_label.setText(str(self.pl_exp))
        self.pl_tx_power_value_label.setText(str(self.pl_tx_power) + " dBm")
        self.pl_tx_gain_value_label.setText(str(self.pl_tx_gain) + " dB")
        self.pl_rx_gain_value_label.setText(str(self.pl_rx_gain) + " dB")
        self.pl_bs_height_value_label.setText(str(self.pl_bs_height) + " m")
        self.pl_ue_height_value_label.setText(str(self.pl_ue_height) + " m")
        if self.signal_dataset:
            self.plUpdatePlot()

    def updateCellMap(self):
        points = self.cell.data_points
        lon_series = np.array([point.lon for point in points], dtype=float)
        lat_series = np.array([point.lat for point in points], dtype=float)

        if self.cbar:
            self.cbar.remove()
        self.map_canvas.axes.cla()
        divider = make_axes_locatable(self.map_canvas.axes)
        cax = divider.append_axes("right", size="5%", pad=0.1)
        self.map_canvas.axes.imshow(self.signal_dataset.plot_map, zorder=0, extent = self.signal_dataset.map_bbox[0], aspect="equal")
        powerscatter = self.map_canvas.axes.scatter(lon_series, lat_series, zorder=1, alpha=1.0, s=20, c=self.cell.signal_power, cmap=self.signal_dataset.cm)

        self.map_canvas.axes.set_xlim(self.signal_dataset.map_bbox[0][0], self.signal_dataset.map_bbox[0][1])
        self.map_canvas.axes.set_ylim(self.signal_dataset.map_bbox[0][2], self.signal_dataset.map_bbox[0][3])
        self.map_canvas.axes.set_xlabel("Longitude")
        self.map_canvas.axes.set_ylabel("Latitude")
        self.map_canvas.axes.set_title("Signal Power vs Position")
        self.cbar = self.map_canvas.fig.colorbar(powerscatter, cax=cax)
        self.cbar.ax.set_ylabel("Signal Power (dBm)", rotation=270, labelpad=10)

        self.map_canvas.draw()

    def brUpdateMeasurements(self):
        points = self.bitrate_dataset.get_points()
        self.br_distances = [utils.get_distance(bitrate.lat, bitrate.lon, self.tower_lat, self.tower_lon) * 1000 for bitrate in points]
        self.br_up = [bitrate.up for bitrate in points]
        self.br_down = [bitrate.down for bitrate in points]
        self.br_up_line.setData(self.br_distances, self.br_up)
        self.br_down_line.setData(self.br_distances, self.br_down)

    def brUpdatePlot(self):
        self.brUpdateMeasurements()

    def plUpdatePlot(self):
        self.plUpdateMeasurements()
        self.plUpdateModels()
        self.plUpdateXScale()
        self.plUpdateYScale()

    def plUpdateXScale(self):
        self.pl_widget.setXRange(0, max(self.cell_distances) + 50)

    def plUpdateYScale(self):
        if self.pl_path_gain:
            y_min = max(self.cell_pl) * -1 - 20
            y_max = min(self.cell_pl) * -1 + 20
        else:
            y_min = min(self.cell_pl) - 20
            y_max = max(self.cell_pl) + 20
        self.pl_widget.setYRange(y_min, y_max)

    def plUpdateMeasurements(self):
        self.cell_distances = self.cell.get_distances(self.tower_lat, self.tower_lon)
        self.cell_pl = self.cell.get_path_loss(self.pl_tx_power)
        if self.pl_path_gain:
            measured_inverted = [element * -1 for element in self.cell_pl]
            self.pl_measured_line.setData(self.cell_distances, measured_inverted)
        else:
            self.pl_measured_line.setData(self.cell_distances, self.cell_pl)

    def plUpdateModels(self):
        if self.pl_fs_checkbox.isChecked():
            self.fs_model = md.FreeSpaceModel(self.pl_freq)
            self.fs_y = self.fs_model.v_path_loss(self.pl_points) - self.pl_tx_gain - self.pl_rx_gain
            if self.pl_path_gain:
                fs_inverted = [element * -1 for element in self.fs_y]
                self.pl_fs_line.setData(self.pl_points, fs_inverted)
            else:
                self.pl_fs_line.setData(self.pl_points, self.fs_y)
        else:
            self.pl_fs_line.clear()

        if self.pl_comp_checkbox.isChecked():
            self.comp_model = md.CompositeModel(freq=self.pl_freq, bs_height=self.pl_bs_height, ue_height=self.pl_ue_height)
            self.comp_y = self.comp_model.v_path_loss(self.pl_points) - self.pl_tx_gain - self.pl_rx_gain
            if self.pl_path_gain:
                comp_inverted = [element * -1 for element in self.comp_y]
                self.pl_comp_line.setData(self.pl_points, comp_inverted)
            else:
                self.pl_comp_line.setData(self.pl_points, self.comp_y)
        else:
            self.pl_comp_line.clear()

        if self.pl_ci_checkbox.isChecked():
            self.ci_model = md.CIModel(freq=self.pl_freq, pl_exp=self.pl_exp, sigma=self.pl_sigma, ref_dist=self.pl_ref_dist)
            self.ci_y = self.ci_model.v_path_loss(self.pl_points) - self.pl_tx_gain - self.pl_rx_gain
            if self.pl_path_gain:
                ci_inverted = [element * -1 for element in self.ci_y]
                self.pl_ci_line.setData(self.pl_points, ci_inverted)
            else:
                self.pl_ci_line.setData(self.pl_points, self.ci_y)
        else:
            self.pl_ci_line.clear()

        if self.pl_abg_checkbox.isChecked():
            self.abg_model = md.ABGModel(freq=self.pl_freq, alpha=self.pl_alpha, beta=self.pl_beta, gamma=self.pl_gamma, sigma=self.pl_sigma, ref_dist=self.pl_ref_dist, ref_freq=self.pl_ref_freq)
            self.abg_y = self.abg_model.v_path_loss(self.pl_points) - self.pl_tx_gain - self.pl_rx_gain
            if self.pl_path_gain:
                abg_inverted = [element * -1 for element in self.abg_y]
                self.pl_abg_line.setData(self.pl_points, abg_inverted)
            else:
                self.pl_abg_line.setData(self.pl_points, self.abg_y)
        else:
            self.pl_abg_line.clear()

        if self.pl_oh_u_checkbox.isChecked():
            self.ohu_model = md.OHUrbanModel(freq=self.pl_freq, bs_height=self.pl_bs_height, ue_height=self.pl_ue_height, large_city=self.pl_large_city)
            self.pl_oh_u_y = self.ohu_model.v_path_loss(self.pl_points) - self.pl_tx_gain - self.pl_rx_gain
            if self.pl_path_gain:
                oh_u_inverted = [element * -1 for element in self.pl_oh_u_y]
                self.pl_oh_u_line.setData(self.pl_points, oh_u_inverted)
            else:
                self.pl_oh_u_line.setData(self.pl_points, self.pl_oh_u_y)
        else:
            self.pl_oh_u_line.clear()

        if self.pl_oh_s_checkbox.isChecked():
            self.ohs_model = md.OHSuburbanModel(freq=self.pl_freq, bs_height=self.pl_bs_height, ue_height=self.pl_ue_height, large_city=self.pl_large_city)
            self.pl_oh_s_y = self.ohs_model.v_path_loss(self.pl_points) - self.pl_tx_gain - self.pl_rx_gain
            if self.pl_path_gain:
                oh_s_inverted = [element * -1 for element in self.pl_oh_s_y]
                self.pl_oh_s_line.setData(self.pl_points, oh_s_inverted)
            else:
                self.pl_oh_s_line.setData(self.pl_points, self.pl_oh_s_y)
        else:
            self.pl_oh_s_line.clear()

        if self.pl_oh_r_checkbox.isChecked():
            self.ohr_model = md.OHRuralModel(freq=self.pl_freq, bs_height=self.pl_bs_height, ue_height=self.pl_ue_height, large_city=self.pl_large_city)
            self.pl_oh_r_y = self.ohr_model.v_path_loss(self.pl_points) - self.pl_tx_gain - self.pl_rx_gain
            if self.pl_path_gain:
                oh_r_inverted = [element * -1 for element in self.pl_oh_r_y]
                self.pl_oh_r_line.setData(self.pl_points, oh_r_inverted)
            else:
                self.pl_oh_r_line.setData(self.pl_points, self.pl_oh_r_y)
        else:
            self.pl_oh_r_line.clear()

def main():
    app = QtWidgets.QApplication(sys.argv)
    w = WSWindow()
    w.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
